//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

public class EquipmentStatusModifierEffect : EquipmentEffect{

	float StrMod = 0;
	float LukMod = 0;
	float IntMod = 0;
	float DexMod = 0;

	public EquipmentStatusModifierEffect(float StrMod, float LukMod, float IntMod, float DexMod){
		this.StrMod = StrMod;
		this.LukMod = LukMod;
		this.IntMod = IntMod;
		this.DexMod = DexMod;
	}

	public override EquipmentEffect.EquipmentModifier GetOnEquipEffect(){
		EquipmentEffect.EquipmentModifier effect = delegate(Unit u){
			u.BonusStrength += StrMod;
			u.BonusLuck += LukMod;
			u.BonusIntelligence += IntMod;
			u.BonusDexterity += DexMod;
		};
		return effect;
	}

	public override EquipmentEffect.EquipmentModifier GetOnUnequipEffect(){
		EquipmentEffect.EquipmentModifier effect = delegate(Unit u){
			u.BonusStrength -= StrMod;
			u.BonusLuck -= LukMod;
			u.BonusIntelligence -= IntMod;
			u.BonusDexterity -= DexMod;
		};
		return effect;
	}

}


